# StyLua configuration file for Neovim LazyVim setup
# https://github.com/JohnnyMorganz/StyLua

# Column width to try to fit code within
column_width = 120

# Type of indents to use
indent_type = "Spaces"

# Size of indents (2 spaces for Neovim config)
indent_width = 2

# Quote style for strings - can be "AutoPreferDouble", "AutoPreferSingle", "ForceDouble", "ForceSingle"
quote_style = "AutoPreferDouble"

# Whether to use require calls as references for imports
call_parentheses = "Always"

# Collapse simple statements onto a single line
collapse_simple_statement = "Never"